spring:
  datasource:
    url: jdbc:mysql://palpites-pro-betting-data-db.cwfr0mbk6bxr.us-east-1.rds.amazonaws.com:3306/mysql
    username: persanti
    password: copodeagua1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
